runtime:
  device: "cuda"
  window_sec: 0.5
  hop_sec: 0.1
  fs_eeg: 250.0
  fs_ecg: 250.0
  eeg_channels: "auto"
  eeg_channel_names: "auto"
  source: "serial12hex"
  source_args:
    port: "/dev/ttyUSB0"
    baudrate: 115200
    head: 255
    tail: 254
    fs: 250.0
    scale_eeg: 1.0
    scale_ecg: 1.0
    eeg_channels: 8
    ecg_channels: 4

preprocess:
  eeg:
    bandpass: [1.0, 45.0]
    notch: "auto"
    normalize: true
  ecg:
    bandpass: [0.5, 40.0]
    normalize: true

labels:
  names: ["00", "01", "10", "11"]